openapi: 3.0.1
info:
  title: AnimeWorld Rest Api
  description: 'AnimeWorld Rest Api'
  version: 0.0.1
servers:
- url: http://localhost:8000
  description: Test server
- url: https://www.animeworld.so/api
  description: Production server
tags:
- name: General
  description: Endpoint genereci
paths:
  /search/v2:
    post:
      tags:
      - General
      summary: Ricerca anime
      description: Ricerca anime nel sito in base ad una chiave di ricerca.
      parameters:
      - name: keyword
        in: query
        description: chiave di ricerca
        required: true
        schema:
          type: string
      - name: csrf-token
        in: header
        description: cross-site request forgery token
        required: true
        schema:
          type: string
      - name: sessionId
        in: cookie
        description: ID di sessione
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ""
  /download/{epID}:
    post:
      tags:
      - General
      summary: Informazioni di download
      description: Restituisce informazioni per il download dell'episodio richiesto.
      parameters:
      - name: epID
        in: path
        description: id episodio
        required: true
        schema:
          type: integer
      - name: csrf-token
        in: header
        description: cross-site request forgery token
        required: true
        schema:
          type: string
  /tooltip/{animeID}:
    get:
      tags:
      - General
      summary: Informazioni generali anime
      description: Restituisce informazioni generali e sintetiche sull'anime.
      parameters:
      - name: animeID
        in: path
        description: id anime
        required: true
        schema:
          type: integer
      - name: csrf-token
        in: header
        description: cross-site request forgery token
        required: true
        schema:
          type: string
  /schedule:
    get:
      tags:
      - General
      summary: Calendario uscite
      description: Restituisce il calendario delle uscite degli episodi per il giorno
        indicato.
      parameters:
      - name: time
        in: query
        description: timestamp in millisecondi con timezone GMT+2
        required: true
        schema:
          type: integer
          default: 1687471200000
      responses:
        '200':
          description: ""
components: {}