openapi: 3.0.1
info:
  title: AnimeWorld Rest Api
  description: 'AnimeWorld Rest Api'
  version: 0.0.1
servers:
- url: http://127.0.0.1:8000/api
  description: Test server
- url: https://www.animeworld.so/api
  description: Production server
tags:
- name: General
  description: Endpoint genereci
- name: Anime
  description: Endpoint riguardanti gli anime
paths:
  /search/v2:
    post:
      tags:
      - General
      summary: Ricerca anime
      description: Ricerca anime nel sito in base ad una chiave di ricerca.
      parameters:
      - name: keyword
        in: query
        description: chiave di ricerca
        required: true
        schema:
          type: string
      - name: Csrf-Token
        in: header
        description: cross-site request forgery token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ""
      security:
      - sessionId: []
  /download/{epID}:
    post:
      tags:
      - Anime
      summary: Informazioni di download
      description: Restituisce informazioni per il download dell'episodio richiesto.
      parameters:
      - name: epID
        in: path
        description: id episodio
        required: true
        schema:
          type: integer
      - name: Csrf-Token
        in: header
        description: cross-site request forgery token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ""
      security:
      - sessionId: []
  /tooltip/{animeID}:
    get:
      tags:
      - Anime
      summary: Informazioni generali anime
      description: Restituisce informazioni generali e sintetiche sull'anime.
      parameters:
      - name: animeID
        in: path
        description: id anime
        required: true
        schema:
          type: integer
      - name: Csrf-Token
        in: header
        description: cross-site request forgery token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ""
  /comments/anime/get/{animeID}:
    post:
      tags:
      - Anime
      summary: Commenti utenti anime
      description: Restituisce i commenti degli utenti dell'anime selezionato.
      parameters:
      - name: animeID
        in: path
        description: id anime
        required: true
        schema:
          type: integer
      - name: Csrf-Token
        in: header
        description: cross-site request forgery token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ""
      security:
      - sessionId: []
  /comments/anime/get/{animeID}{epID}:
    post:
      tags:
      - Anime
      summary: Commenti utenti episodio
      description: Restituisce i commenti degli utenti di un episodio dell'anime selezionato.
      parameters:
      - name: animeID
        in: path
        description: id anime
        required: true
        schema:
          type: integer
      - name: epID
        in: path
        description: id episodio
        required: true
        schema:
          type: integer
      - name: Csrf-Token
        in: header
        description: cross-site request forgery token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ""
      security:
      - sessionId: []
  /schedule:
    get:
      tags:
      - General
      summary: Calendario uscite
      description: Restituisce il calendario delle uscite degli episodi per il giorno
        indicato.
      parameters:
      - name: time
        in: query
        description: timestamp in millisecondi con timezone GMT+2
        required: true
        schema:
          type: integer
          default: 1687471200000
      responses:
        '200':
          description: ""
components: 
  securitySchemes:
    sessionId:
      name: sessionId
      type: apiKey
      in: cookie